#!/bin/bash
echo "✅ Yabai config loaded at $(date)" >>~/yabai-load.log

yabai -m rule --add app="CleanShot X" manage=off
yabai -m rule --add app="EyeBreak" manage=off

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Layout: bsp, stack, or float
yabai -m config layout bsp
yabai -m config mouse_modifier ctrl
yabai -m config mouse_drop_action stack

# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six

## Some random global settings
#yabai -m config focus_follows_mouse          autoraise
#yabai -m config focus_follows_mouse          on
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
#yabai -m config window_shadow float
yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity 1.0
#yabai -m config normal_window_opacity        0.97
#yabai -m config window_border                on | off

## some other settings
yabai -m config split_ratio 0.50
# # set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# general space settings
#yabai -m config focused_border_skip_floating  1
#yabai -m config --space 3 layout             float

# Padding
yabai -m config top_padding 2
yabai -m config bottom_padding 2
yabai -m config left_padding 2
yabai -m config right_padding 2

# Mouse behavior
yabai -m config mouse_follows_focus on
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize

# Scratchpad configuration
yabai -m config scratchpad_border on

# Apps not to manage
yabai -m rule --add app="System Settings" sticky=on manage=off

borders active_color=0xff00ff00 inactive_color=0x00000000 width=7.0 &
